/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class AppXpto {
    public String getGreeting() {
        return "Hello World Xpto!";
    }

    public static void main(String[] args) {
        System.out.println(new AppXpto().getGreeting());
    }
}
