/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.time.Duration;

import com.rabbitmq.stream.*;

public class SuperConsumerApplication {

    public static void main(String[] args) throws Exception {

        Environment env = Environment.builder()
                .uri("rabbitmq-stream://admin:admin@rabbitmq-node1:5552")
                .build();
        
        //assercao/declaracao da fila
        env.streamCreator()
                .stream("test-super-stream")
                .superStream()
                
                //.partitions(3)
                 .bindingKeys("key1", "key2", "key3")
                .creator()
                .create();


        Consumer consumer = env
            .consumerBuilder()
            .superStream("test-super-stream")
            .name("test-consumer-nfe")
            .singleActiveConsumer()
            // .autoTrackingStrategy()
            //         .messageCountBeforeStorage(100)
            //         .flushInterval(Duration.ofSeconds(10))
              // por numero de mensagens consumidas - 10.000
              // timeout - 5 segundos
            //.builder()
            .offset(OffsetSpecification.first())
            .messageHandler((offset, message) -> {
                System.out.println("Received message: " + new String(message.getBodyAsBinary()));
                System.out.println("Offset: " + offset.offset());
            })
            .build();

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            try {
                consumer.close();
                env.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }));
    }
}


//offset lag - o offset lag é a diferença do ultimo offset armazenado e o offset do consumidor