/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.rabbitmq.stream.*;

public class ConsumerApplication {

    public static void main(String[] args) throws Exception {

        Environment env = Environment.builder()
                .uri("rabbitmq-stream://admin:admin@rabbitmq-node1:5552")
                .build();
        
        //assercao/declaracao da fila
        env.streamCreator().stream("test-stream").create();

        //consumer (modelo pull)
        Consumer consumer = env
            .consumerBuilder()
            .stream("test-stream")
            .offset(OffsetSpecification.first())
            .messageHandler((offset, message) -> {
                System.out.println("Received message: " + new String(message.getBodyAsBinary()));
                System.out.println("Offset: " + offset.offset());
            })
            .build();

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            try {
                consumer.close();
                env.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }));
    }
}
