### 👉👉👉 ADMIN LOGIN 👈👈👈
# @name admin_jwt_action
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "admin@user.com",
  "password": "admin"
}

###

@adminAccessToken = {{ admin_jwt_action.response.body.access_token }}
@adminRefreshToken = {{ admin_jwt_action.response.body.refresh_token }}

### Logout

POST http://localhost:3000/logout
Content-Type: application/json

{
  "accessToken": "{{adminAccessToken}}",
  "refreshToken": "{{adminRefreshToken}}"
}

###

POST http://localhost:3000/refresh-token
Authorization: Bearer {{ adminRefreshToken }}

###

GET http://localhost:3000/protected
Authorization: Bearer {{ adminAccessToken }}

###

POST http://localhost:3000/csrf-token




### singed double submit cookie
POST http://localhost:3000/protected
Cookie: accessToken={{ adminAccessToken }};csrf-token=V9uw74vS-WP2iHTQBFuV8qba23QkQkcx5VQE
X-CSRF-TOKEN: V9uw74vS-WP2iHTQBFuV8qba23QkQkcx5VQE

#programacao - valor do csrf token - header x-csrf-token

### 👉👉👉 TEACHER1 LOGIN 👈👈👈
# @name teacher1_jwt_action
POST http://localhost:3000/login
Content-Type: application/json
Origin: http://localhost:3000

{
  "email": "teacher1@user.com",
  "password": "teacher1"
}

###

@teacher1AccessToken = {{ teacher1_jwt_action.response.body.access_token }}
@teacher1RefreshToken = {{ teacher1_jwt_action.response.body.refresh_token }}

### 👉👉👉 TEACHER2 LOGIN 👈👈👈
# @name teacher2_jwt_action
POST http://localhost:3000/login
Content-Type: application/json
Origin: http://localhost:3000

{
  "email": "teacher2@user.com",
  "password": "teacher2"
}

###

@teacher2AccessToken = {{ teacher2_jwt_action.response.body.access_token }}
@teacher2RefreshToken = {{ teacher2_jwt_action.response.body.refresh_token }}

### 👉👉👉 STUDENT1 LOGIN 👈👈👈
# @name student1_jwt_action
POST http://localhost:3000/login
Content-Type: application/json
Origin: http://localhost:3000

{
  "email": "student1@user.com",
  "password": "student1"
}

###

@student1AccessToken = {{ student1_jwt_action.response.body.access_token }}
@student1RefreshToken = {{ student1_jwt_action.response.body.refresh_token }}


### Protected Route
GET http://localhost:3000/protected
Authorization: Bearer {{ adminAccessToken }}

###
# @name admin_refresh_token_action
POST http://localhost:3000/refresh-token
Content-Type: application/json

{
  "refresh_token": "{{ adminRefreshToken }}"
}

# CREATE COURSE
###
POST http://localhost:3000/courses
Content-Type: application/json
Authorization: Bearer {{adminAccessToken}}

{
  "name": "NodeJS",
  "code": "nodejs",
  "description": "NodeJS course",
  "credits": 5,
  "semester": 1,
  "teacher_id": 1
}

### Buscar curso do estudante
GET http://localhost:3000/courses/1
Authorization: Bearer {{student1AccessToken}}

###
GET http://localhost:3000/courses/1
Authorization: Bearer {{teacher2AccessToken}}

###
PATCH http://localhost:3000/courses/2
Content-Type: application/json
Authorization: Bearer {{teacher1AccessToken}}

{
  "description": "Updated NodeJS course description"
}