FROM rabbitmq:4.1.0-management

COPY rabbitmq_delayed_message_exchange-4.1.0.ez /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-4.1.0.ez

RUN rabbitmq-plugins enable \
    rabbitmq_mqtt \
    rabbitmq_shovel_management \
    rabbitmq_federation_management \
    rabbitmq_delayed_message_exchange